# Funding options for Agent Identity Protocol
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: ArangoGutierrez
# ko_fi: # Your Ko-fi username
# patreon: # Your Patreon username
# open_collective: # Your Open Collective username
# custom: ["https://your-custom-link.com"]
