# GoReleaser configuration for AIP
# https://goreleaser.com/customization/

version: 2

project_name: aip

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: aip
    main: ./cmd/aip-proxy
    binary: aip
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - src: ../../README.md
      - src: ../../LICENSE
      - examples/*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch
  groups:
    - title: "🚀 Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "🔒 Security"
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "📦 Dependencies"
      regexp: '^.*?deps(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: "🔧 Other"
      order: 999

release:
  github:
    owner: ArangoGutierrez
    name: agent-identity-protocol
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## AIP {{ .Tag }}
    
    The Agent Identity Protocol proxy - **"Sudo for AI Agents"**
    
    ### Installation
    
    **macOS (Apple Silicon)**
    ```bash
    curl -LO https://github.com/ArangoGutierrez/agent-identity-protocol/releases/download/{{ .Tag }}/aip_{{ .Version }}_darwin_arm64.tar.gz
    tar xzf aip_{{ .Version }}_darwin_arm64.tar.gz
    sudo mv aip /usr/local/bin/
    ```
    
    **macOS (Intel)**
    ```bash
    curl -LO https://github.com/ArangoGutierrez/agent-identity-protocol/releases/download/{{ .Tag }}/aip_{{ .Version }}_darwin_amd64.tar.gz
    tar xzf aip_{{ .Version }}_darwin_amd64.tar.gz
    sudo mv aip /usr/local/bin/
    ```
    
    **Linux (x86_64)**
    ```bash
    curl -LO https://github.com/ArangoGutierrez/agent-identity-protocol/releases/download/{{ .Tag }}/aip_{{ .Version }}_linux_amd64.tar.gz
    tar xzf aip_{{ .Version }}_linux_amd64.tar.gz
    sudo mv aip /usr/local/bin/
    ```
  footer: |
    ---
    
    **Full Changelog**: https://github.com/ArangoGutierrez/agent-identity-protocol/compare/{{ .PreviousTag }}...{{ .Tag }}
    
    **Documentation**: https://github.com/ArangoGutierrez/agent-identity-protocol#readme

brews:
  - name: aip
    repository:
      owner: ArangoGutierrez
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    skip_upload: auto
    directory: Formula
    homepage: https://github.com/ArangoGutierrez/agent-identity-protocol
    description: "Agent Identity Protocol - Zero-trust security for AI agents"
    license: Apache-2.0
    test: |
      system "#{bin}/aip", "--help"
    install: |
      bin.install "aip"
