name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below to help us diagnose the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify you've done the following
      options:
        - label: I have searched [existing issues](https://github.com/ArangoGutierrez/agent-identity-protocol/issues) to ensure this bug hasn't been reported
          required: true
        - label: I am using the latest version of AIP
          required: true
        - label: I have read the [documentation](https://github.com/ArangoGutierrez/agent-identity-protocol#readme)
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the behavior
      placeholder: |
        1. Create policy file with...
        2. Run command...
        3. Send request...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: policy
    attributes:
      label: Policy File (agent.yaml)
      description: If applicable, share your policy configuration (redact sensitive data)
      render: yaml
      placeholder: |
        apiVersion: aip.io/v1alpha1
        kind: AgentPolicy
        metadata:
          name: my-policy
        spec:
          allowed_tools:
            - list_files

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Include any error messages or logs (run with `--verbose` for detailed output)
      render: shell
      placeholder: |
        $ ./aip --policy agent.yaml --target "..." --verbose
        [aip-proxy] ...

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of AIP is affected?
      options:
        - Proxy Core
        - Policy Engine
        - DLP Scanner
        - Human-in-the-Loop (UI Prompts)
        - Audit Logging
        - CLI / Flags
        - Cursor Integration
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: AIP Version
      description: Output of `aip --version` or git commit hash
      placeholder: v0.1.0 or commit abc1234
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Linux (x86_64)
        - Linux (ARM64)
        - Windows
        - Other
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version (if building from source)
      placeholder: go1.23.0

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information that might help
