name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched [existing issues](https://github.com/ArangoGutierrez/agent-identity-protocol/issues) to ensure this hasn't been requested
          required: true
        - label: I have read the [roadmap](https://github.com/ArangoGutierrez/agent-identity-protocol#roadmap) to check if this is planned
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area does this feature relate to?
      options:
        - Policy Engine (new rules, constraints)
        - Security (authentication, authorization)
        - DLP (data loss prevention)
        - Human-in-the-Loop (approval workflows)
        - Audit & Observability
        - Integration (Cursor, VSCode, other IDEs)
        - Kubernetes / Cloud Deployment
        - CLI / UX Improvements
        - SDK / Client Libraries
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's your use case?
      placeholder: |
        As a [type of user], I want to [do something] so that [benefit].
        
        Currently, I have to... which is problematic because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working?
      placeholder: |
        I would like AIP to support...
        
        Example configuration:
        ```yaml
        spec:
          new_feature:
            enabled: true
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        1. Alternative A: ...
        2. Alternative B: ...
        3. Current workaround: ...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important for my use case
        - Blocking my adoption of AIP
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute this feature?
      options:
        - label: I would be willing to submit a PR for this feature
        - label: I can help test this feature
        - label: I can help write documentation for this feature

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or references that might help
