# Example AIP Policy Manifest
#
# This file defines what tools an agent is allowed to use.
# The AIP proxy loads this file at startup and enforces these rules
# on every tool/call request.
#
# Usage:
#   aip-proxy --target "python mcp_server.py" --policy examples/agent.yaml
#
# For monitor mode (dry-run), set spec.mode: monitor
# This logs violations but allows requests through for testing policies.

apiVersion: aip.io/v1alpha1
kind: AgentPolicy

metadata:
  name: code-review-agent
  version: "1.0.0"
  owner: platform-team@company.com

spec:
  # Policy enforcement mode:
  #   - "enforce" (default): Block violations, return error to client
  #   - "monitor": Log violations but allow through (dry-run mode)
  #
  # Monitor mode is useful for:
  #   - Testing new policies before enforcement
  #   - Understanding agent behavior in production
  #   - Gradual policy rollout
  mode: enforce

  # ============================================================================
  # METHOD ALLOWLIST (First Line of Defense)
  # ============================================================================
  #
  # Control which JSON-RPC methods are permitted. This is checked BEFORE
  # tool-level policy, preventing bypass attacks via methods like resources/read.
  #
  # If omitted, only safe default methods are allowed:
  #   - tools/call, tools/list (subject to tool policy)
  #   - initialize, initialized, ping (MCP handshake)
  #   - completion/complete, notifications/*
  #
  # SECURITY: The following are BLOCKED by default:
  #   - resources/read, resources/list (can read arbitrary files!)
  #   - prompts/get, prompts/list (can access prompt templates)
  #
  # Uncomment below to explicitly allow additional methods:
  #
  # allowed_methods:
  #   - tools/call
  #   - tools/list
  #   - resources/read    # ⚠️  DANGEROUS: Only enable if you understand the risk
  #   - prompts/list
  #
  # To block specific methods (takes precedence over allowed):
  # denied_methods:
  #   - resources/write
  #   - logging/setLevel

  # ============================================================================
  # TOOL ALLOWLIST
  # ============================================================================
  #
  # Tools that this agent is allowed to invoke.
  # Any tool not in this list will be blocked with a -32001 Forbidden error.
  #
  # Tool names should match exactly what the MCP server reports in tools/list.
  # Common patterns:
  #   - github_get_repo, github_list_pulls, github_create_review
  #   - postgres_query
  #   - slack_post_message
  allowed_tools:
    # GitHub read operations
    - github_get_repo
    - github_list_pulls
    - github_get_pull
    - github_list_commits
    
    # GitHub write operations (limited)
    - github_create_review
    - github_add_comment
    
    # Filesystem operations (read-only)
    - read_file
    - list_directory
    
    # Explicitly NOT allowed (for reference):
    # - github_delete_repo      # Destructive
    # - github_push             # Write to repo
    # - postgres_query          # Database access
    # - slack_post_message      # External communication
    # - exec_command            # Arbitrary code execution

  # ============================================================================
  # PROTECTED PATHS (Policy Self-Modification Defense)
  # ============================================================================
  #
  # Paths that tools may not read, write, or modify.
  # Any tool argument containing a protected path will be BLOCKED.
  #
  # The policy file itself is ALWAYS protected (added automatically).
  # Add additional sensitive paths here:
  #
  protected_paths:
    - ~/.ssh                    # SSH keys
    - ~/.aws/credentials        # AWS credentials
    - ~/.config/gcloud          # GCP credentials
    - .env                      # Environment variables
    - .env.local                # Local environment
    # Note: The policy file (this file) is automatically protected

  # ============================================================================
  # STRICT ARGS MODE (Global Default)
  # ============================================================================
  #
  # When strict_args_default is true, tools reject any arguments not declared
  # in their allow_args. This prevents exfiltration attacks via extra args.
  #
  # Example attack prevented:
  #   Policy validates: url: "^https://github.com/.*"
  #   Attacker sends:   {"url": "https://github.com/ok", "headers": {"X-Exfil": "secret"}}
  #   Without strict:   headers passes through unchecked (BAD!)
  #   With strict:      BLOCKED - "headers" not in allow_args (GOOD!)
  #
  # strict_args_default: false  # Uncomment to enable globally
  #
  # Individual tools can override with strict_args: true/false

  # ============================================================================
  # TOOL RULES
  # ============================================================================
  #
  # Each rule can specify:
  #   - action: "allow" (default), "block", or "ask"
  #   - strict_args: true/false (override global default)
  #   - allow_args: Regex patterns for argument validation
  #
  # Action types:
  #   - "allow": Permit the tool call (subject to arg validation)
  #   - "block": Deny the tool call unconditionally
  #   - "ask":   Prompt user via native OS dialog for approval (Human-in-the-Loop)
  #
  # The "ask" action spawns a native dialog box asking the user to
  # Approve or Deny. If the user doesn't respond within 60 seconds,
  # the request is auto-denied (fail-closed behavior).
  tool_rules:
    # Example: Dangerous tool requires explicit user approval
    - tool: dangerous_tool
      action: ask

    # Example: Shell execution requires approval AND argument validation
    - tool: exec_command
      action: ask
      allow_args:
        command: "^(ls|cat|echo|pwd)\\s.*"  # Only safe read-only commands

    # Example: Database queries allowed but only SELECT statements
    - tool: postgres_query
      action: allow
      allow_args:
        query: "^SELECT\\s+.*"

    # Example: High-security API with strict argument validation
    # Only declared arguments are allowed; extra args are blocked
    - tool: http_request
      strict_args: true
      allow_args:
        url: "^https://api\\.github\\.com/.*"
        method: "^(GET|POST)$"
      # With strict_args: true, these would be BLOCKED:
      #   {"url": "...", "method": "GET", "headers": {...}}  ← headers not declared
      #   {"url": "...", "method": "GET", "body": "..."}     ← body not declared

    # Example: Explicitly block destructive operations
    - tool: github_delete_repo
      action: block

    - tool: drop_table
      action: block

  # DLP (Data Loss Prevention) - Output Redaction
  #
  # The DLP scanner inspects tool responses (downstream) for sensitive data
  # and redacts matches before forwarding to the client. This prevents
  # accidental exposure of PII, API keys, and secrets through tool outputs.
  #
  # When a pattern matches, the sensitive data is replaced with:
  #   [REDACTED:<RuleName>]
  #
  # Each redaction is logged to the audit trail as a DLP_TRIGGERED event.
  #
  # ENCODING DETECTION:
  #   detect_encoding: true enables scanning of base64/hex encoded strings.
  #   This catches bypass attacks where secrets are encoded to evade patterns:
  #     Original:  AKIAIOSFODNN7EXAMPLE
  #     Base64:    QUtJQUlPU0ZPRE5ON0VYQU1QTEU=
  #     Hex:       414b4941494f53464f444e4e374558414d504c45
  #   Without detection, encoded forms would pass through undetected.
  dlp:
    # enabled: true  # Default is true when dlp block is present
    detect_encoding: true  # Decode base64/hex before scanning (recommended)
    filter_stderr: true    # Apply DLP to subprocess error logs (recommended)
    patterns:
      # Email addresses (PII)
      - name: "Email"
        regex: "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}"

      # AWS Access Key IDs (starts with AKIA, ASIA, etc.)
      - name: "AWS Key"
        regex: "(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}"

      # Generic secret patterns (api_key, secret, password with values)
      - name: "Generic Secret"
        regex: "(?i)(api_key|secret|password)\\s*[:=]\\s*['\"]?([a-zA-Z0-9-_]+)['\"]?"

      # Social Security Numbers (US)
      - name: "SSN"
        regex: "\\b\\d{3}-\\d{2}-\\d{4}\\b"

      # Credit Card Numbers (basic pattern - 16 digits with optional separators)
      - name: "Credit Card"
        regex: "\\b(?:\\d{4}[- ]?){3}\\d{4}\\b"

      # GitHub Personal Access Tokens
      - name: "GitHub Token"
        regex: "ghp_[a-zA-Z0-9]{36}"

      # Private keys (PEM format headers)
      - name: "Private Key"
        regex: "-----BEGIN (RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----"
