# Example: AIP v1alpha2 with Identity and Server features
#
# This policy demonstrates the new server-side features in v1alpha2:
# - Agent identity tokens with automatic rotation
# - Server-side HTTP validation endpoint
# - Policy signing (optional)
#
# Use case: Enterprise deployment with centralized policy validation

apiVersion: aip.io/v1alpha2
kind: AgentPolicy
metadata:
  name: enterprise-agent
  version: "1.0.0"
  owner: security-team@company.com
  # Optional: Sign policy for integrity verification
  # signature: "ed25519:YWJjZGVm..."

spec:
  # Enforcement mode
  mode: enforce

  # Allowed tools
  allowed_tools:
    - read_file
    - write_file
    - list_directory
    - search_code
    - run_tests

  # Tool-specific rules
  tool_rules:
    - tool: write_file
      action: allow
      rate_limit: "20/minute"
      allow_args:
        path: "^/workspace/.*"  # Only allow writes to workspace

    - tool: run_tests
      action: ask  # Require human approval for test execution
      rate_limit: "5/hour"

  # Protected paths (auto-includes policy file)
  protected_paths:
    - "~/.ssh"
    - "~/.aws"
    - "~/.config/gcloud"
    - ".env"
    - ".env.*"
    - "**/secrets/**"

  # DLP configuration
  dlp:
    enabled: true
    detect_encoding: true
    patterns:
      - name: "AWS Key"
        regex: "AKIA[0-9A-Z]{16}"
      - name: "Private Key"
        regex: "-----BEGIN (RSA |EC |DSA )?PRIVATE KEY-----"
      - name: "API Token"
        regex: "(?i)(api[_-]?key|token|secret)[\"']?\\s*[:=]\\s*[\"']?[a-zA-Z0-9_-]{20,}"

  # --- NEW IN v1alpha2 ---

  # Agent Identity Configuration
  identity:
    # Enable token generation
    enabled: true

    # Token lifetime (short for security)
    token_ttl: "10m"

    # Rotate tokens before expiry
    rotation_interval: "8m"

    # Require tokens for all requests (enable after testing)
    require_token: true

    # Bind session to process + policy
    session_binding: "strict"

  # Server-Side Validation Configuration
  server:
    # Enable HTTP server
    enabled: true

    # Listen address (localhost only for security)
    listen: "127.0.0.1:9443"

    # TLS configuration (required for non-localhost)
    # tls:
    #   cert: "/etc/aip/tls/cert.pem"
    #   key: "/etc/aip/tls/key.pem"
    #   client_ca: "/etc/aip/tls/ca.pem"  # For mTLS
    #   require_client_cert: true

    # Custom endpoint paths (optional)
    endpoints:
      validate: "/v1/validate"
      health: "/health"
      metrics: "/metrics"
